version = 1

SPDX-PackageName = "reuse-api"
SPDX-PackageSupplier = "Carmen Bianca Bakker <carmenbianca@fsfe.org>"
SPDX-PackageDownloadLocation = "https://git.fsfe.org/reuse/api"

[[annotations]]
path = "reuse_api/badges/**.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Free Software Foundation Europe e.v."
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "reuse_api/templates/**.html"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Free Software Foundation Europe e.V."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "reuse_api/templates/base/**.html"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2015 Omar Abdelhafith <o.arrabi@me.com>", "2019 Free Software Foundation Europe e.V."]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "reuse_api/static/fonts/roboto/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Google"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "reuse_api/static/fonts/fontawesome/webfonts/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Font Awesome"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "reuse_api/static/img/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Free Software Foundation Europe <https://fsfe.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"